<<<<<<< HEAD
<<<<<<< HEAD
version: '3.1'

services:
  odoo:
    image: my-odoo:18.0
    ports:
      - "8069:8069"
    depends_on:
      - db
    volumes:
      - odoo-data:/var/lib/odoo

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  odoo-data:
  db-data:
=======
version: '3.1'

services:
  odoo:
    image: my-odoo:18.0
    ports:
      - "8069:8069"
    depends_on:
      - db
    volumes:
      - odoo-data:/var/lib/odoo

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  odoo-data:
  db-data:
>>>>>>> f87c4b41ca758878d44d39fde45603a04f9e33fd
=======
version: '3.1'

services:
  odoo:
    image: my-odoo:18.0
    ports:
      - "8069:8069"
    depends_on:
      - db
    volumes:
      - odoo-data:/var/lib/odoo

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  odoo-data:
  db-data:
>>>>>>> f87c4b41ca758878d44d39fde45603a04f9e33fd
